volumes:
  postgres_data:

services:
  postgres:
    image: postgres:18-alpine
    container_name: food-umkm-hub-db
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
