[project]
name = "food-umkm-hub-api"
version = "0.1.0"
description = "Backend for IPB Food & UMKM Hub"
requires-python = ">=3.14"
dependencies = [
    "alembic[tz]>=1.18.4",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "boto3>=1.43.14",
    "fastapi[standard]>=0.128.5",
    "phonenumbers>=9.0.29",
    "pyjwt>=2.12.1",
    "sqlalchemy>=2.0.46",
    "uvloop>=0.22.1 ; sys_platform != 'win32'",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.0",
]

[tool.ruff]
target-version="py314"

extend-exclude = [
    "alembic",
]

[tool.ruff.lint]
extend-select = [
    "B",
    "I",
    "UP",
    "FAST",
    "ASYNC",
]

ignore = [
    "E501",
    "FAST003",
]

[tool.pytest]
pythonpath = ["."]
addopts = ["-ra", "-q", "--import-mode=importlib"]
anyio_mode = "auto"
