[project]
name = "food-umkm-hub-api"
version = "0.1.0"
description = "Backend for IPB Food & UMKM Hub"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.5",
    "uvloop>=0.22.1 ; sys_platform != 'win32'",
]

[dependency-groups]
dev = [
    "ruff>=0.15.0",
]

[tool.ruff]
target-version="py314"

[tool.ruff.lint]
extend-select = [
    "B",
    "I",
    "UP",
    "FAST",
    "ASYNC",
]

ignore = [
    "E501",
]
