// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ChangePasswordRequest
 */
export const zChangePasswordRequest = z.object({
    oldPassword: z.string().min(8),
    newPassword: z.string().min(8)
});

/**
 * ConfirmResetPasswordRequest
 */
export const zConfirmResetPasswordRequest = z.object({
    tokenId: z.uuid(),
    token: z.string(),
    newPassword: z.string().min(8)
});

/**
 * EmailChangeRequest
 */
export const zEmailChangeRequest = z.object({
    email: z.email()
});

/**
 * ErrorResponse
 */
export const zErrorResponse = z.object({
    message: z.string(),
    type: z.string().nullable()
});

/**
 * FavoriteStatusResponse
 */
export const zFavoriteStatusResponse = z.object({
    isFavorited: z.boolean()
});

/**
 * LoginRequest
 */
export const zLoginRequest = z.object({
    email: z.email(),
    password: z.string()
});

/**
 * LoginResponse
 */
export const zLoginResponse = z.object({
    accessToken: z.string()
});

/**
 * NumberChangeRequest
 */
export const zNumberChangeRequest = z.object({
    phoneNumber: z.string()
});

/**
 * OrderItemRequest
 */
export const zOrderItemRequest = z.object({
    productId: z.uuid(),
    quantity: z.int().gt(0)
});

/**
 * OrderItemResponse
 */
export const zOrderItemResponse = z.object({
    productId: z.uuid(),
    productName: z.string(),
    productPrice: z.int(),
    quantity: z.int(),
    subtotal: z.int()
});

/**
 * OrderStatus
 */
export const zOrderStatus = z.enum([
    'pending',
    'waiting_for_confirmation',
    'in_process',
    'ready_to_pickup',
    'rejected',
    'failed',
    'completed'
]);

/**
 * PaymentMethod
 */
export const zPaymentMethod = z.enum(['qris', 'cash']);

/**
 * CreateOrderRequest
 */
export const zCreateOrderRequest = z.object({
    storeId: z.uuid(),
    paymentMethod: zPaymentMethod,
    orderItems: z.array(zOrderItemRequest).min(1),
    promoCode: z.string().nullish(),
    notes: z.string().max(500).nullish()
});

/**
 * OrderDetailResponse
 */
export const zOrderDetailResponse = z.object({
    id: z.uuid(),
    studentId: z.uuid(),
    storeId: z.uuid(),
    paymentMethod: zPaymentMethod,
    status: zOrderStatus,
    orderItems: z.array(zOrderItemResponse),
    totalPrice: z.int(),
    createdAt: z.iso.datetime(),
    isReviewed: z.boolean(),
    discountAmount: z.int(),
    promoCode: z.string().nullable(),
    notes: z.string().nullable(),
    paymentProofUrl: z.string().nullable(),
    rejectionReason: z.string().nullable(),
    rejectedAt: z.iso.datetime().nullable(),
    expiresAt: z.iso.datetime()
});

/**
 * ActiveOrderListResponse
 */
export const zActiveOrderListResponse = z.object({
    waitingForConfirmation: z.array(zOrderDetailResponse),
    inProcess: z.array(zOrderDetailResponse),
    readyToPickup: z.array(zOrderDetailResponse)
});

/**
 * OrderSummaryResponse
 */
export const zOrderSummaryResponse = z.object({
    id: z.uuid(),
    studentId: z.uuid(),
    storeId: z.uuid(),
    paymentMethod: zPaymentMethod,
    status: zOrderStatus,
    orderItems: z.array(zOrderItemResponse),
    totalPrice: z.int(),
    createdAt: z.iso.datetime(),
    isReviewed: z.boolean()
});

/**
 * PaginatedResponse[list[OrderSummaryResponse]]
 */
export const zPaginatedResponseListOrderSummaryResponse = z.object({
    page: z.int(),
    pageSize: z.int(),
    total: z.int(),
    data: z.array(zOrderSummaryResponse)
});

/**
 * ProductCategory
 */
export const zProductCategory = z.enum([
    'food',
    'drink',
    'snack',
    'other'
]);

/**
 * CreateProductRequest
 */
export const zCreateProductRequest = z.object({
    name: z.string(),
    price: z.int().gte(0),
    category: zProductCategory,
    photoUrl: z.string().nullish(),
    description: z.string().nullish()
});

/**
 * PromoType
 */
export const zPromoType = z.enum(['fixed', 'percentage']);

/**
 * CreatePromoRequest
 */
export const zCreatePromoRequest = z.object({
    code: z.string(),
    type: zPromoType,
    value: z.int(),
    startDate: z.iso.datetime(),
    endDate: z.iso.datetime(),
    maxUsage: z.int().gte(0).nullish(),
    maxDiscountAmount: z.int().gte(0).nullish(),
    minOrderAmount: z.int().gte(0).nullish()
});

/**
 * PromoDetailResponse
 */
export const zPromoDetailResponse = z.object({
    id: z.uuid(),
    storeId: z.uuid(),
    code: z.string(),
    type: zPromoType,
    value: z.int(),
    maxDiscountAmount: z.int().nullable(),
    minOrderAmount: z.int().nullable(),
    startDate: z.iso.datetime(),
    endDate: z.iso.datetime(),
    maxUsage: z.int().nullable(),
    usageCount: z.int()
});

/**
 * PromoSummaryResponse
 */
export const zPromoSummaryResponse = z.object({
    id: z.uuid(),
    storeId: z.uuid(),
    code: z.string(),
    type: zPromoType,
    value: z.int(),
    maxDiscountAmount: z.int().nullable(),
    minOrderAmount: z.int().nullable(),
    startDate: z.iso.datetime(),
    endDate: z.iso.datetime()
});

/**
 * PaginatedResponse[list[PromoSummaryResponse]]
 */
export const zPaginatedResponseListPromoSummaryResponse = z.object({
    page: z.int(),
    pageSize: z.int(),
    total: z.int(),
    data: z.array(zPromoSummaryResponse)
});

/**
 * RegisterStoreRequest
 */
export const zRegisterStoreRequest = z.object({
    name: z.string(),
    description: z.string(),
    address: z.string(),
    mapsLink: z.string().nullish(),
    photoUrl: z.string().nullish(),
    qrisImageUrl: z.string().nullish()
});

/**
 * RegisterSellerRequest
 */
export const zRegisterSellerRequest = z.object({
    fullName: z.string(),
    email: z.email(),
    phoneNumber: z.string(),
    password: z.string().min(8),
    store: zRegisterStoreRequest
});

/**
 * RegisterStudentRequest
 */
export const zRegisterStudentRequest = z.object({
    fullName: z.string(),
    email: z.email(),
    phoneNumber: z.string(),
    password: z.string().min(8),
    nim: z.string(),
    faculty: z.string(),
    department: z.string()
});

/**
 * RejectOrderRequest
 */
export const zRejectOrderRequest = z.object({
    reason: z.string()
});

/**
 * RejectionNotesRequest
 */
export const zRejectionNotesRequest = z.object({
    notes: z.string().nullish()
});

/**
 * ResendEmailVerificationRequest
 */
export const zResendEmailVerificationRequest = z.object({
    email: z.email()
});

/**
 * ResetPasswordRequest
 */
export const zResetPasswordRequest = z.object({
    email: z.email()
});

/**
 * ReviewItemRequest
 */
export const zReviewItemRequest = z.object({
    productId: z.uuid(),
    rating: z.int().gte(1).lte(5),
    comment: z.string().max(1000).nullish()
});

/**
 * CreateReviewRequest
 */
export const zCreateReviewRequest = z.object({
    reviews: z.array(zReviewItemRequest).min(1)
});

/**
 * ReviewResponse
 */
export const zReviewResponse = z.object({
    id: z.uuid(),
    orderId: z.uuid(),
    productId: z.uuid(),
    rating: z.int(),
    comment: z.string().nullable()
});

/**
 * PaginatedResponse[list[ReviewResponse]]
 */
export const zPaginatedResponseListReviewResponse = z.object({
    page: z.int(),
    pageSize: z.int(),
    total: z.int(),
    data: z.array(zReviewResponse)
});

/**
 * SignUploadResponse
 */
export const zSignUploadResponse = z.object({
    uploadUrl: z.string(),
    fileKey: z.string(),
    publicUrl: z.string(),
    expiresIn: z.int()
});

/**
 * StoreApprovalStatus
 */
export const zStoreApprovalStatus = z.enum([
    'pending',
    'approved',
    'rejected'
]);

/**
 * StoreDetailResponse
 */
export const zStoreDetailResponse = z.object({
    id: z.uuid(),
    name: z.string(),
    photoUrl: z.string().nullable(),
    isOpen: z.boolean(),
    rating: z.number().nullable(),
    totalReviews: z.int(),
    description: z.string(),
    address: z.string(),
    qrisImageUrl: z.string().nullable(),
    mapsLink: z.string().nullable(),
    updatedAt: z.iso.datetime(),
    createdAt: z.iso.datetime()
});

/**
 * TopSellingProductResponse
 */
export const zTopSellingProductResponse = z.object({
    productId: z.uuid(),
    productName: z.string(),
    productImage: z.string().nullable(),
    quantitySold: z.int(),
    revenue: z.int()
});

/**
 * StoreDashboardResponse
 */
export const zStoreDashboardResponse = z.object({
    todayRevenue: z.int(),
    totalOrders: z.int(),
    totalProductsSold: z.int(),
    storeRating: z.number().nullable(),
    reviewCount: z.int(),
    topSellingProducts: z.array(zTopSellingProductResponse)
});

/**
 * UpdateAvailabilityRequest
 */
export const zUpdateAvailabilityRequest = z.object({
    isAvailable: z.boolean()
});

/**
 * UpdatePaymentProofRequest
 */
export const zUpdatePaymentProofRequest = z.object({
    paymentProofUrl: z.string()
});

/**
 * UpdateProductRequest
 */
export const zUpdateProductRequest = z.object({
    name: z.string().nullish(),
    price: z.int().gte(0).nullish(),
    category: zProductCategory.nullish(),
    photoUrl: z.string().nullish(),
    description: z.string().nullish()
});

/**
 * UpdateProfileRequest
 */
export const zUpdateProfileRequest = z.object({
    fullName: z.string().min(3).nullish(),
    avatarUrl: z.string().nullish()
});

/**
 * UpdatePromoRequest
 */
export const zUpdatePromoRequest = z.object({
    code: z.string().nullish(),
    type: zPromoType.nullish(),
    value: z.int().nullish(),
    startDate: z.iso.datetime().nullish(),
    endDate: z.iso.datetime().nullish(),
    maxUsage: z.int().gte(0).nullish(),
    maxDiscountAmount: z.int().gte(0).nullish(),
    minOrderAmount: z.int().gte(0).nullish()
});

/**
 * UpdateStoreRequest
 */
export const zUpdateStoreRequest = z.object({
    name: z.string().nullish(),
    description: z.string().nullish(),
    address: z.string().nullish(),
    photoUrl: z.string().nullish(),
    qrisImageUrl: z.string().nullish(),
    mapsLink: z.string().nullish()
});

/**
 * UpdateStudentRequest
 */
export const zUpdateStudentRequest = z.object({
    fullName: z.string().nullish(),
    avatarUrl: z.string().nullish(),
    nim: z.string().nullish(),
    faculty: z.string().nullish(),
    department: z.string().nullish()
});

/**
 * UploadContext
 */
export const zUploadContext = z.enum([
    'store_photo',
    'qris_image',
    'product_photo',
    'avatar',
    'payment_proof'
]);

/**
 * SignUploadRequest
 */
export const zSignUploadRequest = z.object({
    context: zUploadContext,
    contentType: z.string()
});

/**
 * UserRole
 */
export const zUserRole = z.enum([
    'admin',
    'student',
    'seller'
]);

/**
 * UserStatus
 */
export const zUserStatus = z.enum([
    'active',
    'inactive',
    'suspended'
]);

/**
 * StudentResponse
 */
export const zStudentResponse = z.object({
    id: z.uuid(),
    fullName: z.string(),
    avatarUrl: z.string().nullable(),
    status: zUserStatus,
    role: zUserRole,
    email: z.string(),
    phoneNumber: z.string(),
    emailVerifiedAt: z.iso.datetime().nullable(),
    phoneVerifiedAt: z.iso.datetime().nullable(),
    nim: z.string(),
    faculty: z.string(),
    department: z.string()
});

/**
 * UserDetailResponse
 */
export const zUserDetailResponse = z.object({
    id: z.uuid(),
    fullName: z.string(),
    avatarUrl: z.string().nullable(),
    status: zUserStatus,
    role: zUserRole,
    email: z.string(),
    phoneNumber: z.string(),
    emailVerifiedAt: z.iso.datetime().nullable(),
    phoneVerifiedAt: z.iso.datetime().nullable()
});

/**
 * StoreWithOwnerDetailResponse
 */
export const zStoreWithOwnerDetailResponse = z.object({
    id: z.uuid(),
    name: z.string(),
    photoUrl: z.string().nullable(),
    rating: z.number().nullable(),
    totalReviews: z.int(),
    approvalStatus: zStoreApprovalStatus,
    owner: zUserDetailResponse,
    description: z.string(),
    address: z.string(),
    qrisImageUrl: z.string().nullable(),
    mapsLink: z.string().nullable(),
    approvalNotes: z.string().nullable(),
    updatedAt: z.iso.datetime(),
    createdAt: z.iso.datetime()
});

/**
 * StoreWithOwnerSummaryResponse
 */
export const zStoreWithOwnerSummaryResponse = z.object({
    id: z.uuid(),
    name: z.string(),
    photoUrl: z.string().nullable(),
    rating: z.number().nullable(),
    totalReviews: z.int(),
    approvalStatus: zStoreApprovalStatus,
    owner: zUserDetailResponse
});

/**
 * PaginatedResponse[list[StoreWithOwnerSummaryResponse]]
 */
export const zPaginatedResponseListStoreWithOwnerSummaryResponse = z.object({
    page: z.int(),
    pageSize: z.int(),
    total: z.int(),
    data: z.array(zStoreWithOwnerSummaryResponse)
});

/**
 * UserSummaryResponse
 */
export const zUserSummaryResponse = z.object({
    id: z.uuid(),
    fullName: z.string(),
    avatarUrl: z.string().nullable(),
    status: zUserStatus,
    role: zUserRole
});

/**
 * PaginatedResponse[list[UserSummaryResponse]]
 */
export const zPaginatedResponseListUserSummaryResponse = z.object({
    page: z.int(),
    pageSize: z.int(),
    total: z.int(),
    data: z.array(zUserSummaryResponse)
});

/**
 * ValidatePromoRequest
 */
export const zValidatePromoRequest = z.object({
    code: z.string(),
    storeId: z.uuid(),
    orderAmount: z.int().gte(0)
});

/**
 * ValidatePromoResponse
 */
export const zValidatePromoResponse = z.object({
    promoId: z.uuid(),
    promoCode: z.string(),
    discountAmount: z.int(),
    finalAmount: z.int()
});

/**
 * ValidationErrorItem
 */
export const zValidationErrorItem = z.object({
    field: z.string(),
    message: z.string()
});

/**
 * ValidationErrorResponse
 */
export const zValidationErrorResponse = z.object({
    message: z.string(),
    type: z.literal('validation_error').optional().default('validation_error'),
    errors: z.array(zValidationErrorItem)
});

/**
 * VerifyPhoneRequest
 */
export const zVerifyPhoneRequest = z.object({
    otp: z.string()
});

/**
 * VerifyTokenRequest
 */
export const zVerifyTokenRequest = z.object({
    tokenId: z.uuid(),
    token: z.string()
});

/**
 * StoreSummaryResponse
 */
export const zAppProductsSchemaStoreSummaryResponse = z.object({
    id: z.uuid(),
    name: z.string(),
    photoUrl: z.string().nullable(),
    rating: z.number().nullable(),
    totalReviews: z.int()
});

/**
 * ProductDetailResponse
 */
export const zProductDetailResponse = z.object({
    id: z.uuid(),
    store: zAppProductsSchemaStoreSummaryResponse,
    name: z.string(),
    price: z.int().gte(0),
    photoUrl: z.string().nullable(),
    category: zProductCategory,
    isAvailable: z.boolean(),
    rating: z.number().nullable(),
    description: z.string().nullable(),
    totalReviews: z.int()
});

/**
 * ProductSummaryResponse
 */
export const zProductSummaryResponse = z.object({
    id: z.uuid(),
    store: zAppProductsSchemaStoreSummaryResponse,
    name: z.string(),
    price: z.int().gte(0),
    photoUrl: z.string().nullable(),
    category: zProductCategory,
    isAvailable: z.boolean(),
    rating: z.number().nullable()
});

/**
 * PaginatedResponse[list[ProductSummaryResponse]]
 */
export const zPaginatedResponseListProductSummaryResponse = z.object({
    page: z.int(),
    pageSize: z.int(),
    total: z.int(),
    data: z.array(zProductSummaryResponse)
});

/**
 * StoreSummaryResponse
 */
export const zAppStoresSchemaStoreSummaryResponse = z.object({
    id: z.uuid(),
    name: z.string(),
    photoUrl: z.string().nullable(),
    isOpen: z.boolean(),
    rating: z.number().nullable(),
    totalReviews: z.int()
});

/**
 * PaginatedResponse[list[StoreSummaryResponse]]
 */
export const zPaginatedResponseListStoreSummaryResponse = z.object({
    page: z.int(),
    pageSize: z.int(),
    total: z.int(),
    data: z.array(zAppStoresSchemaStoreSummaryResponse)
});

/**
 * Successful Response
 */
export const zDeleteCurrentUserUsersMeDeleteResponse = z.void();

/**
 * Successful Response
 */
export const zGetMeUsersMeGetResponse = zUserDetailResponse;

export const zUpdateCurrentProfileUsersMePatchBody = zUpdateProfileRequest;

/**
 * Successful Response
 */
export const zUpdateCurrentProfileUsersMePatchResponse = zUserDetailResponse;

export const zRequestEmailChangeUsersMeEmailPostBody = zEmailChangeRequest;

/**
 * Successful Response
 */
export const zRequestEmailChangeUsersMeEmailPostResponse = z.void();

/**
 * Successful Response
 */
export const zResendEmailChangeVerificationUsersMeEmailResendPostResponse = z.void();

export const zChangePhoneNumberUsersMePhonePostBody = zNumberChangeRequest;

/**
 * Successful Response
 */
export const zChangePhoneNumberUsersMePhonePostResponse = zUserDetailResponse;

export const zVerifyPhoneUsersMePhoneVerifyPostBody = zVerifyPhoneRequest;

/**
 * Successful Response
 */
export const zVerifyPhoneUsersMePhoneVerifyPostResponse = z.void();

/**
 * Successful Response
 */
export const zResendPhoneOtpUsersMePhoneResendPostResponse = z.void();

export const zChangePasswordUsersMePasswordPostBody = zChangePasswordRequest;

/**
 * Successful Response
 */
export const zChangePasswordUsersMePasswordPostResponse = z.void();

export const zRegisterStudentAuthStudentRegisterPostBody = zRegisterStudentRequest;

export const zRegisterUmkmAuthSellerRegisterPostBody = zRegisterSellerRequest;

export const zLoginAuthLoginPostBody = zLoginRequest;

/**
 * Successful Response
 */
export const zLoginAuthLoginPostResponse = zLoginResponse;

export const zVerifyEmailAuthEmailVerifyPostBody = zVerifyTokenRequest;

/**
 * Successful Response
 */
export const zVerifyEmailAuthEmailVerifyPostResponse = z.void();

export const zResendEmailVerificationAuthEmailResendPostBody = zResendEmailVerificationRequest;

/**
 * Successful Response
 */
export const zResendEmailVerificationAuthEmailResendPostResponse = z.void();

export const zVerifyEmailChangeAuthEmailChangeVerifyPostBody = zVerifyTokenRequest;

/**
 * Successful Response
 */
export const zVerifyEmailChangeAuthEmailChangeVerifyPostResponse = z.void();

export const zRequestResetPasswordAuthPasswordResetPostBody = zResetPasswordRequest;

/**
 * Successful Response
 */
export const zRequestResetPasswordAuthPasswordResetPostResponse = z.void();

export const zConfirmResetPasswordAuthPasswordResetConfirmPostBody = zConfirmResetPasswordRequest;

/**
 * Successful Response
 */
export const zConfirmResetPasswordAuthPasswordResetConfirmPostResponse = z.void();

/**
 * Successful Response
 */
export const zGetMeStudentsMeGetResponse = zStudentResponse;

export const zUpdateStudentsMePatchBody = zUpdateStudentRequest;

/**
 * Successful Response
 */
export const zUpdateStudentsMePatchResponse = zStudentResponse;

export const zListStoresGetQuery = z.object({
    is_open: z.boolean().nullish(),
    search: z.string().nullish(),
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zListStoresGetResponse = zPaginatedResponseListStoreSummaryResponse;

/**
 * Successful Response
 */
export const zGetMeStoresMeGetResponse = zStoreDetailResponse;

export const zPatchMeStoresMePatchBody = zUpdateStoreRequest;

/**
 * Successful Response
 */
export const zPatchMeStoresMePatchResponse = zStoreDetailResponse;

/**
 * Successful Response
 */
export const zGetMyDashboardStoresMeDashboardGetResponse = zStoreDashboardResponse;

/**
 * Successful Response
 */
export const zOpenMeStoresMeOpenPostResponse = z.void();

/**
 * Successful Response
 */
export const zCloseMeStoresMeClosePostResponse = z.void();

/**
 * Successful Response
 */
export const zResubmitApplicationStoresMeResubmitPostResponse = z.void();

export const zGetDetailStoresIdGetPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetDetailStoresIdGetResponse = zStoreDetailResponse;

export const zGetAllProductsProductsGetQuery = z.object({
    store_open: z.boolean().nullish(),
    available: z.boolean().nullish(),
    category: zProductCategory.nullish(),
    search: z.string().nullish(),
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zGetAllProductsProductsGetResponse = zPaginatedResponseListProductSummaryResponse;

export const zCreateProductProductsPostBody = zCreateProductRequest;

/**
 * Successful Response
 */
export const zCreateProductProductsPostResponse = zProductDetailResponse;

export const zDeleteProductProductsIdDeletePath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteProductProductsIdDeleteResponse = z.void();

export const zGetProductDetailsProductsIdGetPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetProductDetailsProductsIdGetResponse = zProductDetailResponse;

export const zUpdateProductInformationProductsIdPatchBody = zUpdateProductRequest;

export const zUpdateProductInformationProductsIdPatchPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateProductInformationProductsIdPatchResponse = zProductDetailResponse;

export const zUpdateProductAvailabilityProductsIdAvailabilityPatchBody = zUpdateAvailabilityRequest;

export const zUpdateProductAvailabilityProductsIdAvailabilityPatchPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateProductAvailabilityProductsIdAvailabilityPatchResponse = zProductDetailResponse;

export const zGetMyProductsStoresMeProductsGetQuery = z.object({
    available: z.boolean().nullish(),
    category: zProductCategory.nullish(),
    search: z.string().nullish(),
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zGetMyProductsStoresMeProductsGetResponse = zPaginatedResponseListProductSummaryResponse;

export const zGetProductsByStoreStoresStoreIdProductsGetPath = z.object({
    store_id: z.uuid()
});

export const zGetProductsByStoreStoresStoreIdProductsGetQuery = z.object({
    available: z.boolean().nullish(),
    category: zProductCategory.nullish(),
    search: z.string().nullish(),
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zGetProductsByStoreStoresStoreIdProductsGetResponse = zPaginatedResponseListProductSummaryResponse;

export const zCreatePromoPromosPostBody = zCreatePromoRequest;

/**
 * Successful Response
 */
export const zCreatePromoPromosPostResponse = zPromoDetailResponse;

export const zValidatePromoPromosValidatePostBody = zValidatePromoRequest;

/**
 * Successful Response
 */
export const zValidatePromoPromosValidatePostResponse = zValidatePromoResponse;

export const zDeletePromoPromosIdDeletePath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeletePromoPromosIdDeleteResponse = z.void();

export const zGetPromoDetailsPromosIdGetPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetPromoDetailsPromosIdGetResponse = zPromoDetailResponse;

export const zUpdatePromoInformationPromosIdPatchBody = zUpdatePromoRequest;

export const zUpdatePromoInformationPromosIdPatchPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdatePromoInformationPromosIdPatchResponse = zPromoDetailResponse;

export const zGetAllMeStoresMePromosGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zGetAllMeStoresMePromosGetResponse = zPaginatedResponseListPromoSummaryResponse;

export const zGetAllPromoStoresStoreIdPromosGetPath = z.object({
    store_id: z.uuid()
});

export const zGetAllPromoStoresStoreIdPromosGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zGetAllPromoStoresStoreIdPromosGetResponse = zPaginatedResponseListPromoSummaryResponse;

export const zGetOrdersByStudentOrdersGetQuery = z.object({
    status: zOrderStatus.nullish(),
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zGetOrdersByStudentOrdersGetResponse = zPaginatedResponseListOrderSummaryResponse;

export const zCreateOrderOrdersPostBody = zCreateOrderRequest;

/**
 * Successful Response
 */
export const zCreateOrderOrdersPostResponse = zOrderDetailResponse;

export const zGetOrderDetailsOrdersIdGetPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetOrderDetailsOrdersIdGetResponse = zOrderDetailResponse;

export const zUpdatePaymentProofOrdersIdPaymentProofPostBody = zUpdatePaymentProofRequest;

export const zUpdatePaymentProofOrdersIdPaymentProofPostPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdatePaymentProofOrdersIdPaymentProofPostResponse = zOrderDetailResponse;

export const zCancelOrderOrdersIdCancelPostPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zCancelOrderOrdersIdCancelPostResponse = zOrderDetailResponse;

/**
 * Successful Response
 */
export const zGetAllActiveStoresMeOrdersActiveGetResponse = zActiveOrderListResponse;

export const zGetAllSellerStoresMeOrdersGetQuery = z.object({
    status: zOrderStatus.nullish(),
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zGetAllSellerStoresMeOrdersGetResponse = zPaginatedResponseListOrderSummaryResponse;

export const zAcceptOrderStoresMeOrdersIdAcceptPostPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zAcceptOrderStoresMeOrdersIdAcceptPostResponse = zOrderDetailResponse;

export const zMarkOrderAsReadyToPickupStoresMeOrdersIdReadyPostPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zMarkOrderAsReadyToPickupStoresMeOrdersIdReadyPostResponse = zOrderDetailResponse;

export const zCompleteOrderStoresMeOrdersIdCompletePostPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zCompleteOrderStoresMeOrdersIdCompletePostResponse = zOrderDetailResponse;

export const zRejectOrderStoresMeOrdersIdRejectPostBody = zRejectOrderRequest;

export const zRejectOrderStoresMeOrdersIdRejectPostPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zRejectOrderStoresMeOrdersIdRejectPostResponse = zOrderDetailResponse;

export const zReconsiderOrderRejectionStoresMeOrdersIdReconsiderPostPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zReconsiderOrderRejectionStoresMeOrdersIdReconsiderPostResponse = zOrderDetailResponse;

export const zGetOrderReviewsOrdersIdReviewsGetPath = z.object({
    id: z.uuid()
});

/**
 * Response Get Order Reviews Orders  Id  Reviews Get
 *
 * Successful Response
 */
export const zGetOrderReviewsOrdersIdReviewsGetResponse = z.array(zReviewResponse);

export const zCreateOrderReviewsOrdersIdReviewsPostBody = zCreateReviewRequest;

export const zCreateOrderReviewsOrdersIdReviewsPostPath = z.object({
    id: z.uuid()
});

/**
 * Response Create Order Reviews Orders  Id  Reviews Post
 *
 * Successful Response
 */
export const zCreateOrderReviewsOrdersIdReviewsPostResponse = z.array(zReviewResponse);

export const zGetProductReviewsProductsIdReviewsGetPath = z.object({
    id: z.uuid()
});

export const zGetProductReviewsProductsIdReviewsGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zGetProductReviewsProductsIdReviewsGetResponse = zPaginatedResponseListReviewResponse;

export const zGetStoreReviewsStoresIdReviewsGetPath = z.object({
    id: z.uuid()
});

export const zGetStoreReviewsStoresIdReviewsGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zGetStoreReviewsStoresIdReviewsGetResponse = zPaginatedResponseListReviewResponse;

export const zListFavoriteStoresFavoritesStoresGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zListFavoriteStoresFavoritesStoresGetResponse = zPaginatedResponseListStoreSummaryResponse;

export const zRemoveStoreFavoriteFavoritesStoresStoreIdDeletePath = z.object({
    store_id: z.uuid()
});

/**
 * Successful Response
 */
export const zRemoveStoreFavoriteFavoritesStoresStoreIdDeleteResponse = z.void();

export const zAddStoreFavoriteFavoritesStoresStoreIdPostPath = z.object({
    store_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAddStoreFavoriteFavoritesStoresStoreIdPostResponse = z.void();

export const zGetStoreFavoriteStatusFavoritesStoresStoreIdStatusGetPath = z.object({
    store_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetStoreFavoriteStatusFavoritesStoresStoreIdStatusGetResponse = zFavoriteStatusResponse;

export const zListFavoriteProductsFavoritesProductsGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zListFavoriteProductsFavoritesProductsGetResponse = zPaginatedResponseListProductSummaryResponse;

export const zRemoveProductFavoriteFavoritesProductsProductIdDeletePath = z.object({
    product_id: z.uuid()
});

/**
 * Successful Response
 */
export const zRemoveProductFavoriteFavoritesProductsProductIdDeleteResponse = z.void();

export const zAddProductFavoriteFavoritesProductsProductIdPostPath = z.object({
    product_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAddProductFavoriteFavoritesProductsProductIdPostResponse = z.void();

export const zGetProductFavoriteStatusFavoritesProductsProductIdStatusGetPath = z.object({
    product_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetProductFavoriteStatusFavoritesProductsProductIdStatusGetResponse = zFavoriteStatusResponse;

export const zSignUploadUploadSignPostBody = zSignUploadRequest;

/**
 * Successful Response
 */
export const zSignUploadUploadSignPostResponse = zSignUploadResponse;

export const zListUsersAdminUsersGetQuery = z.object({
    status: zUserStatus.nullish(),
    role: zUserRole.nullish(),
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zListUsersAdminUsersGetResponse = zPaginatedResponseListUserSummaryResponse;

export const zDeleteTargetUserAdminUsersIdDeletePath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteTargetUserAdminUsersIdDeleteResponse = z.void();

export const zSuspendTargetUserAdminUsersIdSuspendPostPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zSuspendTargetUserAdminUsersIdSuspendPostResponse = z.void();

export const zUnsuspendTargetUserAdminUsersIdUnsuspendPostPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zUnsuspendTargetUserAdminUsersIdUnsuspendPostResponse = z.void();

export const zListAllAdminStoresGetQuery = z.object({
    search: z.string().nullish(),
    status: zStoreApprovalStatus.nullish(),
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(16)
});

/**
 * Successful Response
 */
export const zListAllAdminStoresGetResponse = zPaginatedResponseListStoreWithOwnerSummaryResponse;

export const zGetStoreWithOwnerDetailsAdminStoresIdGetPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetStoreWithOwnerDetailsAdminStoresIdGetResponse = zStoreWithOwnerDetailResponse;

export const zApproveApplicationAdminStoresIdApprovePostPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zApproveApplicationAdminStoresIdApprovePostResponse = z.void();

/**
 * Payload
 */
export const zRejectApplicationAdminStoresIdRejectPostBody = zRejectionNotesRequest.nullable();

export const zRejectApplicationAdminStoresIdRejectPostPath = z.object({
    id: z.uuid()
});

/**
 * Successful Response
 */
export const zRejectApplicationAdminStoresIdRejectPostResponse = z.void();
