"""add promo_code column to orders table

Revision ID: cf9175eb19df
Revises: 2f795329b486
Create Date: 2026-05-18 21:04:28.658203+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9175eb19df'
down_revision: Union[str, Sequence[str], None] = '2f795329b486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('promo_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'promo_code')
    # ### end Alembic commands ###
