"""create orders and order_items tables

Revision ID: 2f795329b486
Revises: 792d01da9c84
Create Date: 2026-05-18 16:11:16.031896+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f795329b486'
down_revision: Union[str, Sequence[str], None] = '792d01da9c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('promo_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'WAITING_FOR_CONFIRMATION', 'IN_PROCESS', 'READY_TO_PICKUP', 'REJECTED', 'FAILED', 'COMPLETED', name='orderstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('QRIS', 'CASH', name='paymentmethod'), nullable=False),
    sa.Column('total_price', sa.BigInteger(), nullable=False),
    sa.Column('discount_amount', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('payment_proof_url', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['promo_id'], ['promos.id'], name=op.f('fk_orders_promo_id_promos')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_orders_store_id_stores')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_orders_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_price', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    op.execute('DROP TYPE IF EXISTS orderstatus')
    op.execute('DROP TYPE IF EXISTS paymentmethod')
    # ### end Alembic commands ###
