"""create promos table

Revision ID: 792d01da9c84
Revises: 57695a1211a8
Create Date: 2026-05-17 14:36:51.687097+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792d01da9c84'
down_revision: Union[str, Sequence[str], None] = '57695a1211a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('FIXED', 'PERCENTAGE', name='promotype'), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('max_discount_amount', sa.BigInteger(), nullable=True),
    sa.Column('min_order_amount', sa.BigInteger(), nullable=True),
    sa.Column('max_usage', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_promos_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promos'))
    )
    op.create_index('ix_promos_store_code_active_only', 'promos', ['store_id', 'code'], unique=True, postgresql_where=sa.text('deleted_at is NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_promos_store_code_active_only', table_name='promos', postgresql_where=sa.text('deleted_at is NULL'))
    op.drop_table('promos')
    op.execute('DROP TYPE IF EXISTS promotype')
    # ### end Alembic commands ###
