"""remove timestamp on students table

Revision ID: 7cc209caa50e
Revises: 3fd35d24de83
Create Date: 2026-05-16 01:17:47.709564+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cc209caa50e'
down_revision: Union[str, Sequence[str], None] = '3fd35d24de83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'created_at')
    op.drop_column('students', 'updated_at')
    op.execute("ALTER TYPE tokentype RENAME TO verificationtokentype")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE verificationtokentype RENAME TO tokentype")
    op.add_column('students', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
