"""change price type to int

Revision ID: 3fd35d24de83
Revises: cfc44d446d66
Create Date: 2026-05-11 00:24:51.337099+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd35d24de83'
down_revision: Union[str, Sequence[str], None] = 'cfc44d446d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=0),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=12, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
