"""add orders partial index

Revision ID: bb8c54ff08b3
Revises: a9d41f84376b
Create Date: 2026-05-28 03:59:29.725833+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8c54ff08b3'
down_revision: Union[str, Sequence[str], None] = 'a9d41f84376b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_expires_at', 'orders', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_expires_at', table_name='orders', postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###
