"""add_order_completed_at

Revision ID: 71632e9430e5
Revises: bb8c54ff08b3
Create Date: 2026-06-01 07:22:04.973369+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71632e9430e5"
down_revision: Union[str, Sequence[str], None] = "bb8c54ff08b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_order_items_order_id", "order_items", ["order_id"], unique=False
    )
    op.add_column(
        "orders", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.execute("UPDATE orders SET completed_at = updated_at WHERE status = 'COMPLETED'")
    op.create_index(
        "ix_orders_store_completed_at",
        "orders",
        ["store_id", "completed_at"],
        unique=False,
        postgresql_where=sa.text("status = 'COMPLETED'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_orders_store_completed_at",
        table_name="orders",
        postgresql_where=sa.text("status = 'COMPLETED'"),
    )
    op.drop_column("orders", "completed_at")
    op.drop_index("ix_order_items_order_id", table_name="order_items")
    # ### end Alembic commands ###
