"""rename enum type

Revision ID: 57695a1211a8
Revises: 7cc209caa50e
Create Date: 2026-05-16 06:37:22.606723+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57695a1211a8'
down_revision: Union[str, Sequence[str], None] = '7cc209caa50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE approvalstatus RENAME TO storeapprovalstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE storeapprovalstatus RENAME TO approvalstatus")
    # ### end Alembic commands ###
