/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangeEmailRouteImport } from './routes/change-email'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as VerifyEmailSuccessRouteImport } from './routes/verify-email.success'
import { Route as RegisterCheckEmailRouteImport } from './routes/register.check-email'
import { Route as RegisterRoleRouteImport } from './routes/register.$role'
import { Route as ChangeEmailSuccessRouteImport } from './routes/change-email.success'
import { Route as AuthenticatedStoresRouteImport } from './routes/_authenticated.stores'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated.seller'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated.favorites'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated.checkout'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated.cart'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated.activity'
import { Route as RegisterRoleIndexRouteImport } from './routes/register.$role.index'
import { Route as AuthenticatedStoresIndexRouteImport } from './routes/_authenticated.stores.index'
import { Route as AuthenticatedSellerIndexRouteImport } from './routes/_authenticated.seller.index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated.profile.index'
import { Route as RegisterRoleDetailsRouteImport } from './routes/register.$role.details'
import { Route as AuthenticatedStoresStoreIdRouteImport } from './routes/_authenticated.stores.$storeId'
import { Route as AuthenticatedSellerPromosRouteImport } from './routes/_authenticated.seller.promos'
import { Route as AuthenticatedSellerProfileRouteImport } from './routes/_authenticated.seller.profile'
import { Route as AuthenticatedSellerProductsRouteImport } from './routes/_authenticated.seller.products'
import { Route as AuthenticatedSellerOrdersRouteImport } from './routes/_authenticated.seller.orders'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated.profile.edit'
import { Route as AuthenticatedProfileChangePasswordRouteImport } from './routes/_authenticated.profile.change-password'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated.products.$productId'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated.orders.$orderId'
import { Route as AuthenticatedSellerPromosIndexRouteImport } from './routes/_authenticated.seller.promos.index'
import { Route as AuthenticatedSellerProfileIndexRouteImport } from './routes/_authenticated.seller.profile.index'
import { Route as AuthenticatedSellerProductsIndexRouteImport } from './routes/_authenticated.seller.products.index'
import { Route as AuthenticatedSellerPromosNewRouteImport } from './routes/_authenticated.seller.promos.new'
import { Route as AuthenticatedSellerProfileEditStoreRouteImport } from './routes/_authenticated.seller.profile.edit-store'
import { Route as AuthenticatedSellerProfileEditAccountRouteImport } from './routes/_authenticated.seller.profile.edit-account'
import { Route as AuthenticatedSellerProfileChangePasswordRouteImport } from './routes/_authenticated.seller.profile.change-password'
import { Route as AuthenticatedSellerProductsNewRouteImport } from './routes/_authenticated.seller.products.new'
import { Route as AuthenticatedOrdersOrderIdPaymentRouteImport } from './routes/_authenticated.orders.$orderId_.payment'
import { Route as AuthenticatedOrdersOrderIdSuccessRouteImport } from './routes/_authenticated.orders.$orderId.success'
import { Route as AuthenticatedStoresStoreIdProductsProductIdRouteImport } from './routes/_authenticated.stores.$storeId_.products.$productId'
import { Route as AuthenticatedSellerPromosPromoIdEditRouteImport } from './routes/_authenticated.seller.promos.$promoId.edit'
import { Route as AuthenticatedSellerProductsProductIdEditRouteImport } from './routes/_authenticated.seller.products.$productId.edit'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeEmailRoute = ChangeEmailRouteImport.update({
  id: '/change-email',
  path: '/change-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const VerifyEmailSuccessRoute = VerifyEmailSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => VerifyEmailRoute,
} as any)
const RegisterCheckEmailRoute = RegisterCheckEmailRouteImport.update({
  id: '/register/check-email',
  path: '/register/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoleRoute = RegisterRoleRouteImport.update({
  id: '/register/$role',
  path: '/register/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeEmailSuccessRoute = ChangeEmailSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => ChangeEmailRoute,
} as any)
const AuthenticatedStoresRoute = AuthenticatedStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const RegisterRoleIndexRoute = RegisterRoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRoleRoute,
} as any)
const AuthenticatedStoresIndexRoute =
  AuthenticatedStoresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStoresRoute,
  } as any)
const AuthenticatedSellerIndexRoute =
  AuthenticatedSellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const RegisterRoleDetailsRoute = RegisterRoleDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => RegisterRoleRoute,
} as any)
const AuthenticatedStoresStoreIdRoute =
  AuthenticatedStoresStoreIdRouteImport.update({
    id: '/$storeId',
    path: '/$storeId',
    getParentRoute: () => AuthenticatedStoresRoute,
  } as any)
const AuthenticatedSellerPromosRoute =
  AuthenticatedSellerPromosRouteImport.update({
    id: '/promos',
    path: '/promos',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerProfileRoute =
  AuthenticatedSellerProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerProductsRoute =
  AuthenticatedSellerProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerOrdersRoute =
  AuthenticatedSellerOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileChangePasswordRoute =
  AuthenticatedProfileChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSellerPromosIndexRoute =
  AuthenticatedSellerPromosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSellerPromosRoute,
  } as any)
const AuthenticatedSellerProfileIndexRoute =
  AuthenticatedSellerProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSellerProfileRoute,
  } as any)
const AuthenticatedSellerProductsIndexRoute =
  AuthenticatedSellerProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSellerProductsRoute,
  } as any)
const AuthenticatedSellerPromosNewRoute =
  AuthenticatedSellerPromosNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSellerPromosRoute,
  } as any)
const AuthenticatedSellerProfileEditStoreRoute =
  AuthenticatedSellerProfileEditStoreRouteImport.update({
    id: '/edit-store',
    path: '/edit-store',
    getParentRoute: () => AuthenticatedSellerProfileRoute,
  } as any)
const AuthenticatedSellerProfileEditAccountRoute =
  AuthenticatedSellerProfileEditAccountRouteImport.update({
    id: '/edit-account',
    path: '/edit-account',
    getParentRoute: () => AuthenticatedSellerProfileRoute,
  } as any)
const AuthenticatedSellerProfileChangePasswordRoute =
  AuthenticatedSellerProfileChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedSellerProfileRoute,
  } as any)
const AuthenticatedSellerProductsNewRoute =
  AuthenticatedSellerProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSellerProductsRoute,
  } as any)
const AuthenticatedOrdersOrderIdPaymentRoute =
  AuthenticatedOrdersOrderIdPaymentRouteImport.update({
    id: '/orders/$orderId_/payment',
    path: '/orders/$orderId/payment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrderIdSuccessRoute =
  AuthenticatedOrdersOrderIdSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AuthenticatedOrdersOrderIdRoute,
  } as any)
const AuthenticatedStoresStoreIdProductsProductIdRoute =
  AuthenticatedStoresStoreIdProductsProductIdRouteImport.update({
    id: '/$storeId_/products/$productId',
    path: '/$storeId/products/$productId',
    getParentRoute: () => AuthenticatedStoresRoute,
  } as any)
const AuthenticatedSellerPromosPromoIdEditRoute =
  AuthenticatedSellerPromosPromoIdEditRouteImport.update({
    id: '/$promoId/edit',
    path: '/$promoId/edit',
    getParentRoute: () => AuthenticatedSellerPromosRoute,
  } as any)
const AuthenticatedSellerProductsProductIdEditRoute =
  AuthenticatedSellerProductsProductIdEditRouteImport.update({
    id: '/$productId/edit',
    path: '/$productId/edit',
    getParentRoute: () => AuthenticatedSellerProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/change-email': typeof ChangeEmailRouteWithChildren
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/stores': typeof AuthenticatedStoresRouteWithChildren
  '/change-email/success': typeof ChangeEmailSuccessRoute
  '/register/$role': typeof RegisterRoleRouteWithChildren
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/verify-email/success': typeof VerifyEmailSuccessRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRouteWithChildren
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/profile/change-password': typeof AuthenticatedProfileChangePasswordRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/seller/products': typeof AuthenticatedSellerProductsRouteWithChildren
  '/seller/profile': typeof AuthenticatedSellerProfileRouteWithChildren
  '/seller/promos': typeof AuthenticatedSellerPromosRouteWithChildren
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/register/$role/details': typeof RegisterRoleDetailsRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/seller/': typeof AuthenticatedSellerIndexRoute
  '/stores/': typeof AuthenticatedStoresIndexRoute
  '/register/$role/': typeof RegisterRoleIndexRoute
  '/orders/$orderId/success': typeof AuthenticatedOrdersOrderIdSuccessRoute
  '/orders/$orderId/payment': typeof AuthenticatedOrdersOrderIdPaymentRoute
  '/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
  '/seller/profile/change-password': typeof AuthenticatedSellerProfileChangePasswordRoute
  '/seller/profile/edit-account': typeof AuthenticatedSellerProfileEditAccountRoute
  '/seller/profile/edit-store': typeof AuthenticatedSellerProfileEditStoreRoute
  '/seller/promos/new': typeof AuthenticatedSellerPromosNewRoute
  '/seller/products/': typeof AuthenticatedSellerProductsIndexRoute
  '/seller/profile/': typeof AuthenticatedSellerProfileIndexRoute
  '/seller/promos/': typeof AuthenticatedSellerPromosIndexRoute
  '/seller/products/$productId/edit': typeof AuthenticatedSellerProductsProductIdEditRoute
  '/seller/promos/$promoId/edit': typeof AuthenticatedSellerPromosPromoIdEditRoute
  '/stores/$storeId/products/$productId': typeof AuthenticatedStoresStoreIdProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/change-email': typeof ChangeEmailRouteWithChildren
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/change-email/success': typeof ChangeEmailSuccessRoute
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/verify-email/success': typeof VerifyEmailSuccessRoute
  '/': typeof AuthenticatedIndexRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRouteWithChildren
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/profile/change-password': typeof AuthenticatedProfileChangePasswordRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/register/$role/details': typeof RegisterRoleDetailsRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/seller': typeof AuthenticatedSellerIndexRoute
  '/stores': typeof AuthenticatedStoresIndexRoute
  '/register/$role': typeof RegisterRoleIndexRoute
  '/orders/$orderId/success': typeof AuthenticatedOrdersOrderIdSuccessRoute
  '/orders/$orderId/payment': typeof AuthenticatedOrdersOrderIdPaymentRoute
  '/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
  '/seller/profile/change-password': typeof AuthenticatedSellerProfileChangePasswordRoute
  '/seller/profile/edit-account': typeof AuthenticatedSellerProfileEditAccountRoute
  '/seller/profile/edit-store': typeof AuthenticatedSellerProfileEditStoreRoute
  '/seller/promos/new': typeof AuthenticatedSellerPromosNewRoute
  '/seller/products': typeof AuthenticatedSellerProductsIndexRoute
  '/seller/profile': typeof AuthenticatedSellerProfileIndexRoute
  '/seller/promos': typeof AuthenticatedSellerPromosIndexRoute
  '/seller/products/$productId/edit': typeof AuthenticatedSellerProductsProductIdEditRoute
  '/seller/promos/$promoId/edit': typeof AuthenticatedSellerPromosPromoIdEditRoute
  '/stores/$storeId/products/$productId': typeof AuthenticatedStoresStoreIdProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-email': typeof ChangeEmailRouteWithChildren
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/seller': typeof AuthenticatedSellerRouteWithChildren
  '/_authenticated/stores': typeof AuthenticatedStoresRouteWithChildren
  '/change-email/success': typeof ChangeEmailSuccessRoute
  '/register/$role': typeof RegisterRoleRouteWithChildren
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/verify-email/success': typeof VerifyEmailSuccessRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRouteWithChildren
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/profile/change-password': typeof AuthenticatedProfileChangePasswordRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/_authenticated/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/_authenticated/seller/products': typeof AuthenticatedSellerProductsRouteWithChildren
  '/_authenticated/seller/profile': typeof AuthenticatedSellerProfileRouteWithChildren
  '/_authenticated/seller/promos': typeof AuthenticatedSellerPromosRouteWithChildren
  '/_authenticated/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/register/$role/details': typeof RegisterRoleDetailsRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/seller/': typeof AuthenticatedSellerIndexRoute
  '/_authenticated/stores/': typeof AuthenticatedStoresIndexRoute
  '/register/$role/': typeof RegisterRoleIndexRoute
  '/_authenticated/orders/$orderId/success': typeof AuthenticatedOrdersOrderIdSuccessRoute
  '/_authenticated/orders/$orderId_/payment': typeof AuthenticatedOrdersOrderIdPaymentRoute
  '/_authenticated/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
  '/_authenticated/seller/profile/change-password': typeof AuthenticatedSellerProfileChangePasswordRoute
  '/_authenticated/seller/profile/edit-account': typeof AuthenticatedSellerProfileEditAccountRoute
  '/_authenticated/seller/profile/edit-store': typeof AuthenticatedSellerProfileEditStoreRoute
  '/_authenticated/seller/promos/new': typeof AuthenticatedSellerPromosNewRoute
  '/_authenticated/seller/products/': typeof AuthenticatedSellerProductsIndexRoute
  '/_authenticated/seller/profile/': typeof AuthenticatedSellerProfileIndexRoute
  '/_authenticated/seller/promos/': typeof AuthenticatedSellerPromosIndexRoute
  '/_authenticated/seller/products/$productId/edit': typeof AuthenticatedSellerProductsProductIdEditRoute
  '/_authenticated/seller/promos/$promoId/edit': typeof AuthenticatedSellerPromosPromoIdEditRoute
  '/_authenticated/stores/$storeId_/products/$productId': typeof AuthenticatedStoresStoreIdProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-email'
    | '/login'
    | '/verify-email'
    | '/activity'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/profile'
    | '/seller'
    | '/stores'
    | '/change-email/success'
    | '/register/$role'
    | '/register/check-email'
    | '/verify-email/success'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/profile/change-password'
    | '/profile/edit'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/profile'
    | '/seller/promos'
    | '/stores/$storeId'
    | '/register/$role/details'
    | '/profile/'
    | '/seller/'
    | '/stores/'
    | '/register/$role/'
    | '/orders/$orderId/success'
    | '/orders/$orderId/payment'
    | '/seller/products/new'
    | '/seller/profile/change-password'
    | '/seller/profile/edit-account'
    | '/seller/profile/edit-store'
    | '/seller/promos/new'
    | '/seller/products/'
    | '/seller/profile/'
    | '/seller/promos/'
    | '/seller/products/$productId/edit'
    | '/seller/promos/$promoId/edit'
    | '/stores/$storeId/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-email'
    | '/login'
    | '/verify-email'
    | '/activity'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/change-email/success'
    | '/register/check-email'
    | '/verify-email/success'
    | '/'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/profile/change-password'
    | '/profile/edit'
    | '/seller/orders'
    | '/stores/$storeId'
    | '/register/$role/details'
    | '/profile'
    | '/seller'
    | '/stores'
    | '/register/$role'
    | '/orders/$orderId/success'
    | '/orders/$orderId/payment'
    | '/seller/products/new'
    | '/seller/profile/change-password'
    | '/seller/profile/edit-account'
    | '/seller/profile/edit-store'
    | '/seller/promos/new'
    | '/seller/products'
    | '/seller/profile'
    | '/seller/promos'
    | '/seller/products/$productId/edit'
    | '/seller/promos/$promoId/edit'
    | '/stores/$storeId/products/$productId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/change-email'
    | '/login'
    | '/verify-email'
    | '/_authenticated/activity'
    | '/_authenticated/cart'
    | '/_authenticated/checkout'
    | '/_authenticated/favorites'
    | '/_authenticated/profile'
    | '/_authenticated/seller'
    | '/_authenticated/stores'
    | '/change-email/success'
    | '/register/$role'
    | '/register/check-email'
    | '/verify-email/success'
    | '/_authenticated/'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/products/$productId'
    | '/_authenticated/profile/change-password'
    | '/_authenticated/profile/edit'
    | '/_authenticated/seller/orders'
    | '/_authenticated/seller/products'
    | '/_authenticated/seller/profile'
    | '/_authenticated/seller/promos'
    | '/_authenticated/stores/$storeId'
    | '/register/$role/details'
    | '/_authenticated/profile/'
    | '/_authenticated/seller/'
    | '/_authenticated/stores/'
    | '/register/$role/'
    | '/_authenticated/orders/$orderId/success'
    | '/_authenticated/orders/$orderId_/payment'
    | '/_authenticated/seller/products/new'
    | '/_authenticated/seller/profile/change-password'
    | '/_authenticated/seller/profile/edit-account'
    | '/_authenticated/seller/profile/edit-store'
    | '/_authenticated/seller/promos/new'
    | '/_authenticated/seller/products/'
    | '/_authenticated/seller/profile/'
    | '/_authenticated/seller/promos/'
    | '/_authenticated/seller/products/$productId/edit'
    | '/_authenticated/seller/promos/$promoId/edit'
    | '/_authenticated/stores/$storeId_/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangeEmailRoute: typeof ChangeEmailRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerifyEmailRoute: typeof VerifyEmailRouteWithChildren
  RegisterRoleRoute: typeof RegisterRoleRouteWithChildren
  RegisterCheckEmailRoute: typeof RegisterCheckEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-email': {
      id: '/change-email'
      path: '/change-email'
      fullPath: '/change-email'
      preLoaderRoute: typeof ChangeEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/verify-email/success': {
      id: '/verify-email/success'
      path: '/success'
      fullPath: '/verify-email/success'
      preLoaderRoute: typeof VerifyEmailSuccessRouteImport
      parentRoute: typeof VerifyEmailRoute
    }
    '/register/check-email': {
      id: '/register/check-email'
      path: '/register/check-email'
      fullPath: '/register/check-email'
      preLoaderRoute: typeof RegisterCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$role': {
      id: '/register/$role'
      path: '/register/$role'
      fullPath: '/register/$role'
      preLoaderRoute: typeof RegisterRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-email/success': {
      id: '/change-email/success'
      path: '/success'
      fullPath: '/change-email/success'
      preLoaderRoute: typeof ChangeEmailSuccessRouteImport
      parentRoute: typeof ChangeEmailRoute
    }
    '/_authenticated/stores': {
      id: '/_authenticated/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/register/$role/': {
      id: '/register/$role/'
      path: '/'
      fullPath: '/register/$role/'
      preLoaderRoute: typeof RegisterRoleIndexRouteImport
      parentRoute: typeof RegisterRoleRoute
    }
    '/_authenticated/stores/': {
      id: '/_authenticated/stores/'
      path: '/'
      fullPath: '/stores/'
      preLoaderRoute: typeof AuthenticatedStoresIndexRouteImport
      parentRoute: typeof AuthenticatedStoresRoute
    }
    '/_authenticated/seller/': {
      id: '/_authenticated/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof AuthenticatedSellerIndexRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/register/$role/details': {
      id: '/register/$role/details'
      path: '/details'
      fullPath: '/register/$role/details'
      preLoaderRoute: typeof RegisterRoleDetailsRouteImport
      parentRoute: typeof RegisterRoleRoute
    }
    '/_authenticated/stores/$storeId': {
      id: '/_authenticated/stores/$storeId'
      path: '/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdRouteImport
      parentRoute: typeof AuthenticatedStoresRoute
    }
    '/_authenticated/seller/promos': {
      id: '/_authenticated/seller/promos'
      path: '/promos'
      fullPath: '/seller/promos'
      preLoaderRoute: typeof AuthenticatedSellerPromosRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/profile': {
      id: '/_authenticated/seller/profile'
      path: '/profile'
      fullPath: '/seller/profile'
      preLoaderRoute: typeof AuthenticatedSellerProfileRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/products': {
      id: '/_authenticated/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof AuthenticatedSellerProductsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/orders': {
      id: '/_authenticated/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof AuthenticatedSellerOrdersRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/change-password': {
      id: '/_authenticated/profile/change-password'
      path: '/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof AuthenticatedProfileChangePasswordRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seller/promos/': {
      id: '/_authenticated/seller/promos/'
      path: '/'
      fullPath: '/seller/promos/'
      preLoaderRoute: typeof AuthenticatedSellerPromosIndexRouteImport
      parentRoute: typeof AuthenticatedSellerPromosRoute
    }
    '/_authenticated/seller/profile/': {
      id: '/_authenticated/seller/profile/'
      path: '/'
      fullPath: '/seller/profile/'
      preLoaderRoute: typeof AuthenticatedSellerProfileIndexRouteImport
      parentRoute: typeof AuthenticatedSellerProfileRoute
    }
    '/_authenticated/seller/products/': {
      id: '/_authenticated/seller/products/'
      path: '/'
      fullPath: '/seller/products/'
      preLoaderRoute: typeof AuthenticatedSellerProductsIndexRouteImport
      parentRoute: typeof AuthenticatedSellerProductsRoute
    }
    '/_authenticated/seller/promos/new': {
      id: '/_authenticated/seller/promos/new'
      path: '/new'
      fullPath: '/seller/promos/new'
      preLoaderRoute: typeof AuthenticatedSellerPromosNewRouteImport
      parentRoute: typeof AuthenticatedSellerPromosRoute
    }
    '/_authenticated/seller/profile/edit-store': {
      id: '/_authenticated/seller/profile/edit-store'
      path: '/edit-store'
      fullPath: '/seller/profile/edit-store'
      preLoaderRoute: typeof AuthenticatedSellerProfileEditStoreRouteImport
      parentRoute: typeof AuthenticatedSellerProfileRoute
    }
    '/_authenticated/seller/profile/edit-account': {
      id: '/_authenticated/seller/profile/edit-account'
      path: '/edit-account'
      fullPath: '/seller/profile/edit-account'
      preLoaderRoute: typeof AuthenticatedSellerProfileEditAccountRouteImport
      parentRoute: typeof AuthenticatedSellerProfileRoute
    }
    '/_authenticated/seller/profile/change-password': {
      id: '/_authenticated/seller/profile/change-password'
      path: '/change-password'
      fullPath: '/seller/profile/change-password'
      preLoaderRoute: typeof AuthenticatedSellerProfileChangePasswordRouteImport
      parentRoute: typeof AuthenticatedSellerProfileRoute
    }
    '/_authenticated/seller/products/new': {
      id: '/_authenticated/seller/products/new'
      path: '/new'
      fullPath: '/seller/products/new'
      preLoaderRoute: typeof AuthenticatedSellerProductsNewRouteImport
      parentRoute: typeof AuthenticatedSellerProductsRoute
    }
    '/_authenticated/orders/$orderId_/payment': {
      id: '/_authenticated/orders/$orderId_/payment'
      path: '/orders/$orderId/payment'
      fullPath: '/orders/$orderId/payment'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdPaymentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/$orderId/success': {
      id: '/_authenticated/orders/$orderId/success'
      path: '/success'
      fullPath: '/orders/$orderId/success'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdSuccessRouteImport
      parentRoute: typeof AuthenticatedOrdersOrderIdRoute
    }
    '/_authenticated/stores/$storeId_/products/$productId': {
      id: '/_authenticated/stores/$storeId_/products/$productId'
      path: '/$storeId/products/$productId'
      fullPath: '/stores/$storeId/products/$productId'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedStoresRoute
    }
    '/_authenticated/seller/promos/$promoId/edit': {
      id: '/_authenticated/seller/promos/$promoId/edit'
      path: '/$promoId/edit'
      fullPath: '/seller/promos/$promoId/edit'
      preLoaderRoute: typeof AuthenticatedSellerPromosPromoIdEditRouteImport
      parentRoute: typeof AuthenticatedSellerPromosRoute
    }
    '/_authenticated/seller/products/$productId/edit': {
      id: '/_authenticated/seller/products/$productId/edit'
      path: '/$productId/edit'
      fullPath: '/seller/products/$productId/edit'
      preLoaderRoute: typeof AuthenticatedSellerProductsProductIdEditRouteImport
      parentRoute: typeof AuthenticatedSellerProductsRoute
    }
  }
}

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileChangePasswordRoute: typeof AuthenticatedProfileChangePasswordRoute
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileChangePasswordRoute:
    AuthenticatedProfileChangePasswordRoute,
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedSellerProductsRouteChildren {
  AuthenticatedSellerProductsNewRoute: typeof AuthenticatedSellerProductsNewRoute
  AuthenticatedSellerProductsIndexRoute: typeof AuthenticatedSellerProductsIndexRoute
  AuthenticatedSellerProductsProductIdEditRoute: typeof AuthenticatedSellerProductsProductIdEditRoute
}

const AuthenticatedSellerProductsRouteChildren: AuthenticatedSellerProductsRouteChildren =
  {
    AuthenticatedSellerProductsNewRoute: AuthenticatedSellerProductsNewRoute,
    AuthenticatedSellerProductsIndexRoute:
      AuthenticatedSellerProductsIndexRoute,
    AuthenticatedSellerProductsProductIdEditRoute:
      AuthenticatedSellerProductsProductIdEditRoute,
  }

const AuthenticatedSellerProductsRouteWithChildren =
  AuthenticatedSellerProductsRoute._addFileChildren(
    AuthenticatedSellerProductsRouteChildren,
  )

interface AuthenticatedSellerProfileRouteChildren {
  AuthenticatedSellerProfileChangePasswordRoute: typeof AuthenticatedSellerProfileChangePasswordRoute
  AuthenticatedSellerProfileEditAccountRoute: typeof AuthenticatedSellerProfileEditAccountRoute
  AuthenticatedSellerProfileEditStoreRoute: typeof AuthenticatedSellerProfileEditStoreRoute
  AuthenticatedSellerProfileIndexRoute: typeof AuthenticatedSellerProfileIndexRoute
}

const AuthenticatedSellerProfileRouteChildren: AuthenticatedSellerProfileRouteChildren =
  {
    AuthenticatedSellerProfileChangePasswordRoute:
      AuthenticatedSellerProfileChangePasswordRoute,
    AuthenticatedSellerProfileEditAccountRoute:
      AuthenticatedSellerProfileEditAccountRoute,
    AuthenticatedSellerProfileEditStoreRoute:
      AuthenticatedSellerProfileEditStoreRoute,
    AuthenticatedSellerProfileIndexRoute: AuthenticatedSellerProfileIndexRoute,
  }

const AuthenticatedSellerProfileRouteWithChildren =
  AuthenticatedSellerProfileRoute._addFileChildren(
    AuthenticatedSellerProfileRouteChildren,
  )

interface AuthenticatedSellerPromosRouteChildren {
  AuthenticatedSellerPromosNewRoute: typeof AuthenticatedSellerPromosNewRoute
  AuthenticatedSellerPromosIndexRoute: typeof AuthenticatedSellerPromosIndexRoute
  AuthenticatedSellerPromosPromoIdEditRoute: typeof AuthenticatedSellerPromosPromoIdEditRoute
}

const AuthenticatedSellerPromosRouteChildren: AuthenticatedSellerPromosRouteChildren =
  {
    AuthenticatedSellerPromosNewRoute: AuthenticatedSellerPromosNewRoute,
    AuthenticatedSellerPromosIndexRoute: AuthenticatedSellerPromosIndexRoute,
    AuthenticatedSellerPromosPromoIdEditRoute:
      AuthenticatedSellerPromosPromoIdEditRoute,
  }

const AuthenticatedSellerPromosRouteWithChildren =
  AuthenticatedSellerPromosRoute._addFileChildren(
    AuthenticatedSellerPromosRouteChildren,
  )

interface AuthenticatedSellerRouteChildren {
  AuthenticatedSellerOrdersRoute: typeof AuthenticatedSellerOrdersRoute
  AuthenticatedSellerProductsRoute: typeof AuthenticatedSellerProductsRouteWithChildren
  AuthenticatedSellerProfileRoute: typeof AuthenticatedSellerProfileRouteWithChildren
  AuthenticatedSellerPromosRoute: typeof AuthenticatedSellerPromosRouteWithChildren
  AuthenticatedSellerIndexRoute: typeof AuthenticatedSellerIndexRoute
}

const AuthenticatedSellerRouteChildren: AuthenticatedSellerRouteChildren = {
  AuthenticatedSellerOrdersRoute: AuthenticatedSellerOrdersRoute,
  AuthenticatedSellerProductsRoute:
    AuthenticatedSellerProductsRouteWithChildren,
  AuthenticatedSellerProfileRoute: AuthenticatedSellerProfileRouteWithChildren,
  AuthenticatedSellerPromosRoute: AuthenticatedSellerPromosRouteWithChildren,
  AuthenticatedSellerIndexRoute: AuthenticatedSellerIndexRoute,
}

const AuthenticatedSellerRouteWithChildren =
  AuthenticatedSellerRoute._addFileChildren(AuthenticatedSellerRouteChildren)

interface AuthenticatedStoresRouteChildren {
  AuthenticatedStoresStoreIdRoute: typeof AuthenticatedStoresStoreIdRoute
  AuthenticatedStoresIndexRoute: typeof AuthenticatedStoresIndexRoute
  AuthenticatedStoresStoreIdProductsProductIdRoute: typeof AuthenticatedStoresStoreIdProductsProductIdRoute
}

const AuthenticatedStoresRouteChildren: AuthenticatedStoresRouteChildren = {
  AuthenticatedStoresStoreIdRoute: AuthenticatedStoresStoreIdRoute,
  AuthenticatedStoresIndexRoute: AuthenticatedStoresIndexRoute,
  AuthenticatedStoresStoreIdProductsProductIdRoute:
    AuthenticatedStoresStoreIdProductsProductIdRoute,
}

const AuthenticatedStoresRouteWithChildren =
  AuthenticatedStoresRoute._addFileChildren(AuthenticatedStoresRouteChildren)

interface AuthenticatedOrdersOrderIdRouteChildren {
  AuthenticatedOrdersOrderIdSuccessRoute: typeof AuthenticatedOrdersOrderIdSuccessRoute
}

const AuthenticatedOrdersOrderIdRouteChildren: AuthenticatedOrdersOrderIdRouteChildren =
  {
    AuthenticatedOrdersOrderIdSuccessRoute:
      AuthenticatedOrdersOrderIdSuccessRoute,
  }

const AuthenticatedOrdersOrderIdRouteWithChildren =
  AuthenticatedOrdersOrderIdRoute._addFileChildren(
    AuthenticatedOrdersOrderIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRouteWithChildren
  AuthenticatedStoresRoute: typeof AuthenticatedStoresRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRouteWithChildren
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
  AuthenticatedOrdersOrderIdPaymentRoute: typeof AuthenticatedOrdersOrderIdPaymentRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedSellerRoute: AuthenticatedSellerRouteWithChildren,
  AuthenticatedStoresRoute: AuthenticatedStoresRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRouteWithChildren,
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
  AuthenticatedOrdersOrderIdPaymentRoute:
    AuthenticatedOrdersOrderIdPaymentRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ChangeEmailRouteChildren {
  ChangeEmailSuccessRoute: typeof ChangeEmailSuccessRoute
}

const ChangeEmailRouteChildren: ChangeEmailRouteChildren = {
  ChangeEmailSuccessRoute: ChangeEmailSuccessRoute,
}

const ChangeEmailRouteWithChildren = ChangeEmailRoute._addFileChildren(
  ChangeEmailRouteChildren,
)

interface VerifyEmailRouteChildren {
  VerifyEmailSuccessRoute: typeof VerifyEmailSuccessRoute
}

const VerifyEmailRouteChildren: VerifyEmailRouteChildren = {
  VerifyEmailSuccessRoute: VerifyEmailSuccessRoute,
}

const VerifyEmailRouteWithChildren = VerifyEmailRoute._addFileChildren(
  VerifyEmailRouteChildren,
)

interface RegisterRoleRouteChildren {
  RegisterRoleDetailsRoute: typeof RegisterRoleDetailsRoute
  RegisterRoleIndexRoute: typeof RegisterRoleIndexRoute
}

const RegisterRoleRouteChildren: RegisterRoleRouteChildren = {
  RegisterRoleDetailsRoute: RegisterRoleDetailsRoute,
  RegisterRoleIndexRoute: RegisterRoleIndexRoute,
}

const RegisterRoleRouteWithChildren = RegisterRoleRoute._addFileChildren(
  RegisterRoleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangeEmailRoute: ChangeEmailRouteWithChildren,
  LoginRoute: LoginRoute,
  VerifyEmailRoute: VerifyEmailRouteWithChildren,
  RegisterRoleRoute: RegisterRoleRouteWithChildren,
  RegisterCheckEmailRoute: RegisterCheckEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
