/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as VerifyEmailSuccessRouteImport } from './routes/verify-email.success'
import { Route as RegisterCheckEmailRouteImport } from './routes/register.check-email'
import { Route as RegisterRoleRouteImport } from './routes/register.$role'
import { Route as AuthenticatedStoresRouteImport } from './routes/_authenticated.stores'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated.favorites'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated.activity'
import { Route as RegisterRoleIndexRouteImport } from './routes/register.$role.index'
import { Route as RegisterRoleDetailsRouteImport } from './routes/register.$role.details'
import { Route as AuthenticatedStoresStoreIdRouteImport } from './routes/_authenticated.stores.$storeId'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated.products.$productId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const VerifyEmailSuccessRoute = VerifyEmailSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => VerifyEmailRoute,
} as any)
const RegisterCheckEmailRoute = RegisterCheckEmailRouteImport.update({
  id: '/register/check-email',
  path: '/register/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoleRoute = RegisterRoleRouteImport.update({
  id: '/register/$role',
  path: '/register/$role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoresRoute = AuthenticatedStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const RegisterRoleIndexRoute = RegisterRoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegisterRoleRoute,
} as any)
const RegisterRoleDetailsRoute = RegisterRoleDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => RegisterRoleRoute,
} as any)
const AuthenticatedStoresStoreIdRoute =
  AuthenticatedStoresStoreIdRouteImport.update({
    id: '/$storeId',
    path: '/$storeId',
    getParentRoute: () => AuthenticatedStoresRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/stores': typeof AuthenticatedStoresRouteWithChildren
  '/register/$role': typeof RegisterRoleRouteWithChildren
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/verify-email/success': typeof VerifyEmailSuccessRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/register/$role/details': typeof RegisterRoleDetailsRoute
  '/register/$role/': typeof RegisterRoleIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/stores': typeof AuthenticatedStoresRouteWithChildren
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/verify-email/success': typeof VerifyEmailSuccessRoute
  '/': typeof AuthenticatedIndexRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/register/$role/details': typeof RegisterRoleDetailsRoute
  '/register/$role': typeof RegisterRoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/stores': typeof AuthenticatedStoresRouteWithChildren
  '/register/$role': typeof RegisterRoleRouteWithChildren
  '/register/check-email': typeof RegisterCheckEmailRoute
  '/verify-email/success': typeof VerifyEmailSuccessRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/stores/$storeId': typeof AuthenticatedStoresStoreIdRoute
  '/register/$role/details': typeof RegisterRoleDetailsRoute
  '/register/$role/': typeof RegisterRoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/verify-email'
    | '/activity'
    | '/favorites'
    | '/stores'
    | '/register/$role'
    | '/register/check-email'
    | '/verify-email/success'
    | '/products/$productId'
    | '/stores/$storeId'
    | '/register/$role/details'
    | '/register/$role/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/verify-email'
    | '/activity'
    | '/favorites'
    | '/stores'
    | '/register/check-email'
    | '/verify-email/success'
    | '/'
    | '/products/$productId'
    | '/stores/$storeId'
    | '/register/$role/details'
    | '/register/$role'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/verify-email'
    | '/_authenticated/activity'
    | '/_authenticated/favorites'
    | '/_authenticated/stores'
    | '/register/$role'
    | '/register/check-email'
    | '/verify-email/success'
    | '/_authenticated/'
    | '/_authenticated/products/$productId'
    | '/_authenticated/stores/$storeId'
    | '/register/$role/details'
    | '/register/$role/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerifyEmailRoute: typeof VerifyEmailRouteWithChildren
  RegisterRoleRoute: typeof RegisterRoleRouteWithChildren
  RegisterCheckEmailRoute: typeof RegisterCheckEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/verify-email/success': {
      id: '/verify-email/success'
      path: '/success'
      fullPath: '/verify-email/success'
      preLoaderRoute: typeof VerifyEmailSuccessRouteImport
      parentRoute: typeof VerifyEmailRoute
    }
    '/register/check-email': {
      id: '/register/check-email'
      path: '/register/check-email'
      fullPath: '/register/check-email'
      preLoaderRoute: typeof RegisterCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$role': {
      id: '/register/$role'
      path: '/register/$role'
      fullPath: '/register/$role'
      preLoaderRoute: typeof RegisterRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stores': {
      id: '/_authenticated/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/register/$role/': {
      id: '/register/$role/'
      path: '/'
      fullPath: '/register/$role/'
      preLoaderRoute: typeof RegisterRoleIndexRouteImport
      parentRoute: typeof RegisterRoleRoute
    }
    '/register/$role/details': {
      id: '/register/$role/details'
      path: '/details'
      fullPath: '/register/$role/details'
      preLoaderRoute: typeof RegisterRoleDetailsRouteImport
      parentRoute: typeof RegisterRoleRoute
    }
    '/_authenticated/stores/$storeId': {
      id: '/_authenticated/stores/$storeId'
      path: '/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof AuthenticatedStoresStoreIdRouteImport
      parentRoute: typeof AuthenticatedStoresRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedStoresRouteChildren {
  AuthenticatedStoresStoreIdRoute: typeof AuthenticatedStoresStoreIdRoute
}

const AuthenticatedStoresRouteChildren: AuthenticatedStoresRouteChildren = {
  AuthenticatedStoresStoreIdRoute: AuthenticatedStoresStoreIdRoute,
}

const AuthenticatedStoresRouteWithChildren =
  AuthenticatedStoresRoute._addFileChildren(AuthenticatedStoresRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedStoresRoute: typeof AuthenticatedStoresRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedStoresRoute: AuthenticatedStoresRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface VerifyEmailRouteChildren {
  VerifyEmailSuccessRoute: typeof VerifyEmailSuccessRoute
}

const VerifyEmailRouteChildren: VerifyEmailRouteChildren = {
  VerifyEmailSuccessRoute: VerifyEmailSuccessRoute,
}

const VerifyEmailRouteWithChildren = VerifyEmailRoute._addFileChildren(
  VerifyEmailRouteChildren,
)

interface RegisterRoleRouteChildren {
  RegisterRoleDetailsRoute: typeof RegisterRoleDetailsRoute
  RegisterRoleIndexRoute: typeof RegisterRoleIndexRoute
}

const RegisterRoleRouteChildren: RegisterRoleRouteChildren = {
  RegisterRoleDetailsRoute: RegisterRoleDetailsRoute,
  RegisterRoleIndexRoute: RegisterRoleIndexRoute,
}

const RegisterRoleRouteWithChildren = RegisterRoleRoute._addFileChildren(
  RegisterRoleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  VerifyEmailRoute: VerifyEmailRouteWithChildren,
  RegisterRoleRoute: RegisterRoleRouteWithChildren,
  RegisterCheckEmailRoute: RegisterCheckEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
